Repository mandiant/capa, pull requests merged in 2020-07, with the labels that each got.

#150 ci: Add GitHub action for style checkers
  .github/workflows/tests.yml
  capa/features/extractors/viv/__init__.py
  capa/features/freeze.py
  capa/main.py
  capa/render/__init__.py
  doc/installation.md
  scripts/capafmt.py
  scripts/lint.py
  scripts/migrate-rules.py
  scripts/show-capabilities-by-function.py
  scripts/show-features.py
  tests/test_freeze.py
  tests/test_main.py
  tests/test_viv_features.py
Labels: CI, enhancement

#151 Add CI status badge to README
  README.md
Labels: CI, enhancement

#166 Fix rule linter and run it in the CI GitHub action
  .github/workflows/tests.yml
  scripts/lint.py
Labels: bug, enhancement

#175 Add vivisect installation to setup & Add tests to GitHub Actions
  .github/workflows/tests.yml
  README.md
  doc/installation.md
  setup.py
Labels: CI, enhancement

#180 fix #176
  capa/features/extractors/viv/insn.py
  capa/main.py
Labels: bug

#185 main: don't crash when the .viv cannot be saved
  capa/main.py
Labels: bug

#187 Improve documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  doc/installation.md
Labels: documentation

#209 Enable descriptions for statement nodes
  capa/engine.py
  capa/render/__init__.py
  capa/render/vverbose.py
  capa/rules.py
  tests/test_engine.py
  tests/test_rules.py
Labels: enhancement
