Repository mandiant/capa, pull requests merged in 2020-08, with the labels that each got.

#220 ci: enable pyinstaller builds upon gh release tagged
  .github/workflows/build.yml
  setup.py
Labels: CI, enhancement

#221 setup: bump viv version
  .github/workflows/build.yml
  setup.py
Labels: bug

#219 ida: use a local context for cache instead of global
  capa/features/extractors/ida/__init__.py
  capa/features/extractors/ida/insn.py
  tests/test_ida_features.py
Labels: bug

#222 draft v1.1.0 release
  CHANGELOG.md
  capa/version.py
Labels: documentation

#235 main: progress bar updates (+rules, and realize iterators)
  capa/features/extractors/viv/insn.py
  capa/main.py
  setup.py
Labels: enhancement

#238 Fix build workflow & zip binaries
  .github/workflows/build.yml
Labels: CI, enhancement

#239 backport py3 testing enhancements
  .github/workflows/tests.yml
  capa/features/freeze.py
  tests/fixtures.py
  tests/test_freeze.py
  tests/test_main.py
  tests/test_viv_features.py
Labels: enhancement

#269 use vivisect from pypi and other packaging
  .github/pyinstaller/pyinstaller.spec
  .github/workflows/publish.yml
  doc/usage.md
  setup.py
Labels: enhancement
