Repository mandiant/capa, pull requests merged in 2020-09, with the labels that each got.

#272 fix 262
  capa/features/__init__.py
  tests/fixtures.py
  tests/test_main.py
Labels: bug

#273 fix 263
  capa/rules.py
  tests/test_fmt.py
Labels: bug

#277 fix 276
  capa/features/extractors/viv/insn.py
  tests/fixtures.py
Labels: bug

#274 fix 246
  capa/features/extractors/helpers.py
  capa/features/extractors/ida/file.py
  capa/features/extractors/ida/insn.py
  capa/features/extractors/viv/file.py
  capa/features/extractors/viv/insn.py
  tests/fixtures.py
Labels: enhancement

#278 ida: use ida-settings to persist rules directory
  capa/ida/plugin/form.py
  setup.py
Labels: enhancement

#284 render: dont display rules that are also matched as subrule matches
  capa/render/default.py
  tests/test_main.py
Labels: enhancement

#285 ida plugin: add search bar
  capa/ida/plugin/form.py
  capa/ida/plugin/proxy.py
  capa/ida/plugin/view.py
Labels: enhancement

#287 fix 286
  capa/ida/plugin/form.py
  capa/ida/plugin/item.py
  capa/ida/plugin/model.py
  capa/ida/plugin/proxy.py
Labels: enhancement

#296 updates to plugin function-level documentation
  capa/ida/plugin/__init__.py
  capa/ida/plugin/capa_plugin_ida.py
  capa/ida/plugin/form.py
  capa/ida/plugin/hooks.py
  capa/ida/plugin/item.py
  capa/ida/plugin/model.py
  capa/ida/plugin/proxy.py
  capa/ida/plugin/view.py
Labels: documentation, enhancement

#301 ida plugin: don't use rule path settings if the path doesn't exist
  capa/ida/plugin/form.py
Labels: bug

#304 ida plugin: ui improvements
  capa/ida/plugin/__init__.py
  capa/ida/plugin/form.py
  capa/ida/plugin/model.py
Labels: enhancement

#305 ida plugin: highlight regex matches in IDA ui
  capa/ida/plugin/item.py
  capa/ida/plugin/model.py
Labels: enhancement

#308 ida plugin: new name
  capa/ida/plugin/__init__.py
  capa/ida/plugin/capa_explorer.py
  doc/usage.md
Labels: enhancement

#294 docs: installation: clarify when to use method 2
  doc/installation.md
Labels: bug

#314 explorer: progress indicator
  capa/ida/plugin/form.py
Labels: enhancement

#323 use PyYAML CLoader to parse rules when available
  .github/workflows/build.yml
  .github/workflows/tests.yml
  capa/rules.py
Labels: enhancement

#324 scripts: add script demonstrating bulk processing
  scripts/bulk-process.py
Labels: enhancement

#326 main: fix reported total rule count
  capa/main.py
Labels: bug
