Repository mandiant/capa, pull requests merged in 2021-05, with the labels that each got.

#570 show-features: skip library functions
  CHANGELOG.md
  scripts/show-features.py
Labels: bug

#572 linter: summarize status at end
  CHANGELOG.md
  scripts/lint.py
Labels: enhancement

#568 file scope API features
  CHANGELOG.md
  capa/features/__init__.py
  capa/features/extractors/ida/file.py
  capa/features/extractors/smda/file.py
  capa/features/extractors/viv/file.py
  capa/features/file.py
  capa/rules.py
  tests/fixtures.py
  tests/test_rules.py
  tests/test_smda_features.py
Labels: enhancement

#576 render `rule.meta.mbc` on output
  CHANGELOG.md
  capa/render/__init__.py
  capa/render/default.py
  capa/render/utils.py
  capa/render/vverbose.py
  capa/rules.py
Labels: breaking-change
