Repository mandiant/capa, pull requests merged in 2021-03, with the labels that each got.

#452 pyinstaller: update for py3/pyinstaller 4.2
  .github/pyinstaller/hooks/hook-smda.py
  .github/pyinstaller/hooks/hook-vivisect.py
  .github/pyinstaller/pyinstaller.spec
  .github/workflows/build.yml
Labels: enhancement

#450 refactor common cli argument handling
  capa/main.py
  scripts/bulk-process.py
  scripts/capa_as_library.py
  scripts/import-to-ida.py
  scripts/lint.py
  scripts/migrate-rules.py
  scripts/show-capabilities-by-function.py
  scripts/show-features.py
Labels: enhancement

#475 changelog: document incompatibility of viv files
  CHANGELOG.md
Labels: bug, documentation

#491 ci: pin OS versions
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: CI, enhancement

#493 rule generator: support subscope rules
  capa/ida/plugin/form.py
  capa/ida/plugin/view.py
Labels: enhancement

#476 ci: tag capa-rules on release
  .github/workflows/tag.yml
  doc/release.md
Labels: CI, enhancement

#468 add support for string features with special characters e.g. '\n'
  capa/features/__init__.py
  capa/ida/plugin/model.py
  capa/ida/plugin/view.py
  capa/render/vverbose.py
  scripts/lint.py
  tests/test_rules.py
Labels: enhancement
