Repository mandiant/capa, pull requests merged in 2021-06, with the labels that each got.

#593 json: capture all strings matching regex
  CHANGELOG.md
  capa/features/__init__.py
  capa/ida/plugin/model.py
  capa/render/__init__.py
  capa/render/vverbose.py
Labels: breaking-change, enhancement

#591 main: use rule scope internal/limitation/file for file limitations, not code
  CHANGELOG.md
  capa/main.py
  capa/render/__init__.py
  capa/rules.py
  scripts/lint.py
Labels: enhancement

#604 ci: lint CHANGELOG
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: CI

#607 Use Ana06/get-changed-files@v1.2
  .github/workflows/changelog.yml
Labels: CI

#608 fix 605
  CHANGELOG.md
  capa/main.py
Labels: bug

#620 correctly render negative numbers and offsets
  CHANGELOG.md
  capa/features/insn.py
Labels: breaking-change, bug

#624 remove logic from __init__.py and break import cycles
  CHANGELOG.md
  capa/engine.py
  capa/features/__init__.py
  capa/features/basicblock.py
  capa/features/common.py
  capa/features/extractors/__init__.py
  capa/features/extractors/base_extractor.py
  capa/features/extractors/ida/__init__.py
  capa/features/extractors/ida/basicblock.py
  capa/features/extractors/ida/extractor.py
  capa/features/extractors/ida/function.py
  capa/features/extractors/ida/helpers.py
  capa/features/extractors/ida/insn.py
  capa/features/extractors/pefile.py
  capa/features/extractors/smda/__init__.py
  capa/features/extractors/smda/basicblock.py
  capa/features/extractors/smda/extractor.py
  capa/features/extractors/smda/file.py
  capa/features/extractors/smda/function.py
  capa/features/extractors/smda/insn.py
  capa/features/extractors/viv/__init__.py
  capa/features/extractors/viv/basicblock.py
  capa/features/extractors/viv/extractor.py
  capa/features/extractors/viv/file.py
  capa/features/extractors/viv/function.py
  capa/features/extractors/viv/insn.py
  capa/features/file.py
  capa/features/freeze.py
  capa/features/insn.py
  capa/ida/helpers.py
  capa/ida/plugin/form.py
  capa/ida/plugin/item.py
  capa/ida/plugin/model.py
  capa/ida/plugin/view.py
  capa/main.py
  capa/render/__init__.py
  capa/render/default.py
  capa/render/json.py
  capa/render/result_document.py
  capa/render/verbose.py
  capa/render/vverbose.py
  capa/rules.py
  scripts/bulk-process.py
  scripts/capa2yara.py
  scripts/capa_as_library.py
  scripts/lint.py
  scripts/show-capabilities-by-function.py
  scripts/show-features.py
  tests/fixtures.py
  tests/test_engine.py
  tests/test_freeze.py
  tests/test_helpers.py
  tests/test_ida_features.py
  tests/test_main.py
  tests/test_pefile_features.py
  tests/test_render.py
  tests/test_rules.py
  tests/test_smda_features.py
  tests/test_viv_features.py
Labels: breaking-change, bug

#636 move test sigs into testfiles
  sigs/test_aulldiv.pat
  sigs/test_aullrem.pat.gz
  tests/fixtures.py
Labels: enhancement

#621 add type annotations to public routines
  .github/mypy/mypy.ini
  .github/workflows/tests.yml
  CHANGELOG.md
  capa/engine.py
  capa/features/common.py
  capa/features/extractors/base_extractor.py
  capa/features/extractors/helpers.py
  capa/features/extractors/ida/file.py
  capa/features/extractors/pefile.py
  capa/features/extractors/smda/basicblock.py
  capa/features/extractors/smda/function.py
  capa/features/extractors/smda/insn.py
  capa/features/extractors/viv/basicblock.py
  capa/features/extractors/viv/extractor.py
  capa/features/extractors/viv/file.py
  capa/features/extractors/viv/function.py
  capa/features/extractors/viv/helpers.py
  capa/features/extractors/viv/indirect_calls.py
  capa/features/extractors/viv/insn.py
  capa/features/file.py
  capa/features/freeze.py
  capa/features/insn.py
  capa/helpers.py
  capa/ida/plugin/item.py
  capa/main.py
  capa/render/default.py
  capa/render/json.py
  capa/render/result_document.py
  capa/render/utils.py
  capa/render/verbose.py
  capa/render/vverbose.py
  capa/rules.py
  scripts/capa_as_library.py
  scripts/import-to-bn.py
  scripts/lint.py
  setup.py
Labels: breaking-change, enhancement

#640 disable viv creation by default
  CHANGELOG.md
  capa/features/freeze.py
  capa/main.py
  doc/usage.md
  scripts/bulk-process.py
  scripts/capa_as_library.py
  scripts/lint.py
  scripts/show-capabilities-by-function.py
  tests/fixtures.py
Labels: enhancement

#639 more intuitive signature loading
  capa/features/freeze.py
  capa/main.py
  capa/render/result_document.py
  scripts/bulk-process.py
  scripts/show-capabilities-by-function.py
  scripts/show-features.py
Labels: enhancement
