Repository mandiant/capa, pull requests merged in 2021-04, with the labels that each got.

#511 fix submodule typos
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#470 test on Windows, Ubuntu, macOS across Python versions
  .github/workflows/tests.yml
  tests/test_smda_features.py
Labels: CI

#506 build using Py3.8 and test across more OSs
  .github/workflows/build.yml
  CHANGELOG.md
Labels: CI, bug

#528 explorer: readme: document IDA 7.6 patch
  CHANGELOG.md
  capa/ida/plugin/README.md
Labels: documentation

#530 changelog: add v1.6.2
  CHANGELOG.md
Labels: documentation
