Repository mandiant/capa, pull requests merged in 2023-01, with the labels that each got.

#1213 remove SMDA backend
  .github/mypy/mypy.ini
  CHANGELOG.md
  capa/features/extractors/smda/__init__.py
  capa/features/extractors/smda/basicblock.py
  capa/features/extractors/smda/extractor.py
  capa/features/extractors/smda/file.py
  capa/features/extractors/smda/function.py
  capa/features/extractors/smda/global_.py
  capa/features/extractors/smda/insn.py
  capa/main.py
  setup.py
  tests/fixtures.py
  tests/test_main.py
  tests/test_smda_features.py
Labels: breaking-change

#1264 render: verbose: fix rendering of scopes
  CHANGELOG.md
  capa/render/verbose.py
Labels: bug

#1270 features: string: better __str__ embedded whitespace
  CHANGELOG.md
  capa/features/common.py
  capa/features/extractors/common.py
Labels: bug

#1283 better detect invalid rules
  CHANGELOG.md
  capa/rules.py
Labels: bug

#1273 viv: insn: string: handle viv bug around substrings
  CHANGELOG.md
  capa/features/extractors/viv/insn.py
  tests/fixtures.py
Labels: bug

#1294 Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: CI

#1291 cache rule set across invocations of capa
  .github/pyinstaller/pyinstaller.spec
  .github/workflows/build.yml
  CHANGELOG.md
  capa/ida/plugin/cache.py
  capa/ida/plugin/form.py
  capa/main.py
  capa/rules/__init__.py
  capa/rules/cache.py
  scripts/bulk-process.py
  scripts/cache-ruleset.py
  scripts/capa2yara.py
  scripts/capa_as_library.py
  scripts/lint.py
  scripts/profile-time.py
  scripts/show-capabilities-by-function.py
  tests/test_rule_cache.py
  tests/test_rules.py
Labels: enhancement, breaking-change
