Repository mandiant/capa, pull requests merged in 2023-07, with the labels that each got.

#1529 Add Ghidra Backend CI configuration, fix CHANGELOG
  .github/mypy/mypy.ini
  .github/workflows/tests.yml
  CHANGELOG.md
  capa/features/extractors/ghidra/extractor.py
  capa/features/extractors/ghidra/global_.py
  capa/main.py
  tests/fixtures.py
  tests/test_ghidra_features.py
Labels: ghidra, gsoc

#1526 ghidra: Remove redundant imports & objects
  CHANGELOG.md
  capa/features/extractors/ghidra/global_.py
Labels: ghidra, gsoc

#1589 main: don't leave behind traces of the progress bar
  CHANGELOG.md
  capa/main.py
  scripts/lint.py
  scripts/profile-time.py
Labels: enhancement

#1588 use fancy box drawing characters for default output
  CHANGELOG.md
  capa/main.py
  capa/render/default.py
  setup.py
Labels: enhancement

#1564 Add Ghidra File Feature Extraction
  capa/features/extractors/ghidra/extractor.py
  capa/features/extractors/ghidra/file.py
  capa/features/extractors/ghidra/global_.py
  capa/features/extractors/ghidra/helpers.py
  capa/main.py
Labels: ghidra, gsoc

#1613 PyPI trusted publishing
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: enhancement, CI

#1617 ci: restrict permissions of GITHUB_TOKEN
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: CI

#1623 Updated file paths to use pathlib.Path instance
  CHANGELOG.md
  capa/features/extractors/binja/find_binja_api.py
  capa/features/extractors/dnfile/extractor.py
  capa/features/extractors/dnfile_.py
  capa/features/extractors/dotnetfile.py
  capa/features/extractors/elffile.py
  capa/features/extractors/pefile.py
  capa/features/extractors/viv/extractor.py
  capa/features/freeze/__init__.py
  capa/helpers.py
  capa/ida/helpers.py
  capa/ida/plugin/form.py
  capa/main.py
  capa/render/proto/__init__.py
  capa/rules/__init__.py
  capa/rules/cache.py
  scripts/bulk-process.py
  scripts/cache-ruleset.py
  scripts/capa2yara.py
  scripts/capa_as_library.py
  scripts/capafmt.py
  scripts/detect-elf-os.py
  scripts/detect_duplicate_features.py
  scripts/import-to-bn.py
  scripts/lint.py
  scripts/profile-time.py
  scripts/proto-to-results.py
  scripts/setup-linter-dependencies.py
  scripts/show-capabilities-by-function.py
  scripts/show-features.py
  tests/fixtures.py
  tests/test_binja_features.py
  tests/test_freeze.py
  tests/test_ida_features.py
  tests/test_main.py
  tests/test_os_detection.py
  tests/test_pefile_features.py
  tests/test_rule_cache.py
  tests/test_scripts.py
Labels: enhancement

#1612 add process and thread addresses
  .github/ruff.toml
  CHANGELOG.md
  capa/features/address.py
  capa/features/extractors/base_extractor.py
  capa/features/extractors/cape/extractor.py
  capa/features/extractors/cape/file.py
  capa/features/extractors/cape/helpers.py
  capa/features/extractors/cape/process.py
  capa/features/extractors/cape/thread.py
  capa/features/extractors/null.py
  capa/features/freeze/__init__.py
  capa/main.py
  scripts/show-features.py
  tests/fixtures.py
  tests/test_static_freeze.py
Labels: breaking-change, gsoc, dynamic

#1628 introduce flake8-simplify
  .github/flake8.ini
  capa/features/extractors/binja/basicblock.py
  capa/features/extractors/binja/extractor.py
  capa/features/extractors/binja/insn.py
  capa/features/extractors/dnfile/extractor.py
  capa/features/extractors/dnfile/helpers.py
  capa/features/extractors/dnfile/types.py
  capa/features/extractors/elf.py
  capa/features/extractors/ida/helpers.py
  capa/features/extractors/ida/insn.py
  capa/features/extractors/strings.py
  capa/features/extractors/viv/indirect_calls.py
  capa/features/extractors/viv/insn.py
  capa/ida/plugin/cache.py
  capa/ida/plugin/form.py
  capa/ida/plugin/hooks.py
  capa/ida/plugin/item.py
  capa/ida/plugin/model.py
  capa/ida/plugin/view.py
  capa/main.py
  capa/render/vverbose.py
  capa/rules/__init__.py
  pyproject.toml
  scripts/capa2yara.py
  scripts/import-to-bn.py
  scripts/lint.py
  scripts/profile-memory.py
  tests/test_rule_cache.py
Labels: enhancement, CI

#1597 Ghidra: Function Feature Extraction
  capa/features/extractors/ghidra/file.py
  capa/features/extractors/ghidra/function.py
  capa/features/extractors/ghidra/helpers.py
  capa/main.py
Labels: ghidra, gsoc

#1630 fix binja test type error
  capa/main.py
  tests/test_binja_features.py
Labels: bug

#1631 introduce flake8-use-pathlib
  pyproject.toml
Labels: enhancement, CI

#1634 ci: use latest python for best performance
  .github/workflows/tests.yml
Labels: enhancement, CI

#1638 main: log time taken to analyze each function
  CHANGELOG.md
  capa/main.py
Labels: enhancement

#1635 ci: set top level permissions to satisfy code scanning
  .github/workflows/build.yml
  .github/workflows/changelog.yml
  .github/workflows/publish.yml
  .github/workflows/tag.yml
  .github/workflows/tests.yml
Labels: enhancement, CI

#1639 main: don't show spinner when debug messages are emitted
  CHANGELOG.md
  capa/main.py
Labels: bug

#1640 tests: make fixtures available via conftest.py
  .github/ruff.toml
  CHANGELOG.md
  tests/conftest.py
  tests/test_binja_features.py
  tests/test_dnfile_features.py
  tests/test_dotnet_features.py
  tests/test_dotnetfile_features.py
  tests/test_freeze.py
  tests/test_function_id.py
  tests/test_main.py
  tests/test_pefile_features.py
  tests/test_proto.py
  tests/test_result_document.py
  tests/test_viv_features.py
Labels: enhancement, CI

#1637 Ghidra: Basic Block Feature Extraction
  capa/features/extractors/ghidra/basicblock.py
Labels: ghidra, gsoc

#1669 Fix binja backend stack string detection. Re-enable binja stack strin…
  CHANGELOG.md
  capa/features/extractors/binja/basicblock.py
  tests/test_binja_features.py
Labels: bug, binary-ninja
