Repository mandiant/capa, pull requests merged in 2024-08, with the labels that each got.

#2263 add path exclusions to python tests.yml workflow
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: CI

#2267 web: change base url for capa Explorer Web
  web/explorer/src/components/NavBar.vue
  web/explorer/vite.config.js
Labels: webui

#2264 web: separate build and deploy, incorporate landing page
  .github/workflows/web-deploy.yml
  .gitmodules
  web/explorer/vite.config.js
  web/public/img/icon.ico
  web/public/img/icon.png
  web/public/index.html
Labels: webui

#2275 web: add button to download release
  .github/workflows/web-deploy.yml
  web/explorer/package.json
  web/explorer/src/components/NavBar.vue
Labels: webui

#2201 ida extractor: extract APIs from renamed globals
  CHANGELOG.md
  README.md
  capa/features/extractors/ida/insn.py
  capa/ida/plugin/README.md
  pyproject.toml
Labels: enhancement, ida-explorer

#2308 web: add umami script for collecting metrics
  web/explorer/index.html
  web/public/index.html
Labels: enhancement, webui

#2301 web: don't include preview data and options in release mode
  web/explorer/src/components/NavBar.vue
  web/explorer/src/components/RuleMatchesTable.vue
  web/explorer/src/components/UploadOptions.vue
  web/explorer/src/components/columns/RuleColumn.vue
  web/explorer/src/composables/useRdocLoader.js
  web/explorer/src/utils/rdocParser.js
  web/explorer/src/views/ImportView.vue
  web/explorer/vite.config.js
Labels: gsoc, webui

#2324 rules: deduplicate API features with stripped DLL
  CHANGELOG.md
  capa/rules/__init__.py
Labels: bug

#2326 readme: add quick links to header
  README.md
Labels: enhancement

#2325 add .justfile
  .justfile
  CHANGELOG.md
Labels: enhancement

#2312 Edit explorer landing page
  README.md
  web/explorer/DEVELOPMENT.md
  web/explorer/README.md
  web/explorer/index.html
  web/explorer/src/components/DescriptionPanel.vue
  web/explorer/src/components/MetadataPanel.vue
  web/explorer/src/components/NavBar.vue
  web/explorer/src/components/UploadOptions.vue
  web/explorer/src/main.js
Labels: gsoc, webui

#2331 web: fix class feature type
  web/explorer/src/utils/rdocParser.js
Labels: webui

#2338 cli: link to rule names to capa rules website
  .justfile
  CHANGELOG.md
  capa/render/default.py
  tests/test_render.py
  web/explorer/src/components/RuleMatchesTable.vue
  web/explorer/src/utils/urlHelpers.js
  web/public/index.html
  web/rules/.gitignore
  web/rules/scripts/build_root.py
  web/rules/scripts/build_rules.py
Labels: enhancement
