Repository mandiant/capa, pull requests merged in 2024-02, with the labels that each got.

#1969 freeze: remove unused import
  CHANGELOG.md
  capa/features/freeze/__init__.py
Labels: bug

#2001 [CI] Use badge in gist for rules number in README
  README.md
Labels: CI

#2005 [changelog] Add gist badge
  CHANGELOG.md
Labels: documentation

#2004 Fix CHANGELOG PR review & update Ana06/automatic-pull-request-review
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: bug, CI

#2003 [CI] Update GitHub actions to versions using Node 20
  .github/workflows/changelog.yml
  .github/workflows/scorecard.yml
  .github/workflows/tag.yml
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: CI
