Repository mandiant/capa, pull requests merged in 2024-01, with the labels that each got.

#1924 com: move database into python files
  .github/pyinstaller/pyinstaller.spec
  assets/classes.json.gz
  assets/interfaces.json.gz
  capa/features/com/__init__.py
  capa/features/com/classes.py
  capa/features/com/interfaces.py
  capa/rules/__init__.py
Labels: bug

#1925 render: show human readable flavor name
  capa/render/default.py
Labels: bug

#1947 more ELF OS detection techniques
  CHANGELOG.md
  capa/features/extractors/elf.py
Labels: enhancement

#1948 refactor main to for ease of integration
  CHANGELOG.md
  capa/features/common.py
  capa/features/extractors/common.py
  capa/features/freeze/__init__.py
  capa/ghidra/capa_ghidra.py
  capa/helpers.py
  capa/ida/plugin/form.py
  capa/loader.py
  capa/main.py
  capa/rules/__init__.py
  scripts/bulk-process.py
  scripts/cache-ruleset.py
  scripts/capa2yara.py
  scripts/capa_as_library.py
  scripts/capafmt.py
  scripts/detect-elf-os.py
  scripts/detect_duplicate_features.py
  scripts/lint.py
  scripts/match-function-id.py
  scripts/profile-time.py
  scripts/proto-from-results.py
  scripts/proto-to-results.py
  scripts/show-capabilities-by-function.py
  scripts/show-features.py
  scripts/show-unused-features.py
  tests/fixtures.py
Labels: enhancement

#1786 Ghidra: Capa Explorer UI Integration
  CHANGELOG.md
  capa/ghidra/README.md
  capa/ghidra/capa_explorer.py
  capa/main.py
Labels: ghidra
